@echo off
set PROXYS=198.161.14.25:8080
set PROXY=198.161.14.25:8080
IF "%HTTPS_PROXY%"=="" (GOTO TURN_ON) ELSE (GOTO TURN_OFF)

:TURN_ON
	SET HTTPS_PROXY=%PROXYS%
	SET HTTP_PROXY=%PROXY%
	ECHO Turned On Proxy (%PROXYS%)
	GOTO EXIT

:TURN_OFF
	SET HTTPS_PROXY=
	SET HTTP_PROXY=
	ECHO Turned Off Proxy (%PROXYS%)
	GOTO EXIT

:EXIT
